### ISSUE TITLE
makara_adapter: method_missing forces master too often

### ISSUE THREAD

**Issue by lasssim** [taskrabbit/makara#20]
hi,

i just started playing around with your awesome looking makara gem. but i had some troubles getting it to work as i expected.

i used the current master (34558507f3dd) and compared it with the tag v0.1.0.beta4.
#### setup

``` yaml
      adapter: makara_mysql2

      sticky_master:      false
      sticky_slave:       false
      blacklist_duration: 60
      verbose:            true

      database: development
      port:     3306
      encoding: utf8   # not sure if these two settings

      connections:
        - name: db
          role: master
          host: localhost
          username: root
          password: root


        - name: dbslave01
          role: slave
          host: localhost
          username: root
          password: root
          weight: 3

```

this is what i did

``` ruby
User.all
```
#### on master i get

```
  [default/db] SCHEMA (1.2ms)  SHOW FULL FIELDS FROM `users`
  [default/db] SCHEMA (0.3ms)  SHOW TABLES LIKE 'users'
  [default/db] User Load (0.3ms)  SELECT `users`.* FROM `users` WHERE `users`.`deleted_at` IS NULL
```
#### on v0.1.0.beta4 i get

```
  [db] SCHEMA (1.8ms)  SHOW FULL FIELDS FROM `users`
  [dbslave01] SCHEMA (0.4ms)  SHOW TABLES LIKE 'users'
  [dbslave01] User Load (0.3ms)  SELECT `users`.* FROM `users` WHERE `users`.`deleted_at` IS NULL
```

i tried to debug this and with some debug output i found that the problem might be related with the method_missing method in makara_adapter.rb. 

it looks like if you call methods using the with_master block which forces makara to use the master connection. i'm not really sure hot to fix this or if this is intended behavior but i couldn't figure out how to get makara select a slave for a "select" statement.

i also played around with one of your tests (https://gist.github.com/lister/6727346) which seems to work just fine...

it would be great if you could help me.

Br, Simon
