### ISSUE TITLE
Stack level too deep error

### ISSUE THREAD

**Issue by ChrisHughes** [taskrabbit/makara#39]
I'm trying to upgrade an existing rails project that requires master / slave replication and thread safety from DbCharmer to Makara.

This app runs a small script that automatically generates / prunes some required css files when it is starting up.

It needs to perform a select query during this script, so I have followed guides such as this http://exposinggotchas.blogspot.ca/2011/02/activerecord-migrations-without-rails.html to use ActiveRecord outside of rails.

Whenever I use ActiveRecord::Base.establish_connection to either a mysql2 adapter or a mysql2_makara adapter, I get this crash.

```
$ rails s
=> Booting Thin
=> Rails 3.2.16 application starting in development on http://0.0.0.0:3000
=> Call with -d to detach
=> Ctrl-C to shutdown server
Exiting
/Users/user/.rvm/gems/ruby-2.1.0/gems/rack-1.4.5/lib/rack/builder.rb:40: stack level too deep (SystemStackError)
```

The code that is being used

config/application.rb

``` rails
    db_config = YAML::load(File.open("#{Rails.root}/config/database.yml"))[ENV["RAILS_ENV"]]['myawesomedb']
    db_config['adapter'] = 'mysql2'
    ActiveRecord::Base.establish_connection(db_config) 
    somedata = ActiveRecord::Base.connection.execute("SELECT value FROM variables WHERE name='somevariablekey'").first[0]
    ActiveRecord::Base.clear_all_connections!
    ActiveRecord::Base.clear_cache!
```

This error is giving me minimal information to debug with, so I'm wondering if it is a bug, or am I missing something? Should I call this task from the command line as a separate rake task, or is there some way to reset ActiveRecord after using it in this method?

I'm using Rails 3.2.16, Ruby 2.1.0, and an otherwise fairly basic gemset with no other database / activerecord stuff other than makara.

**Comment by mnelson** [comment]
So without makara in the gemfile you have the same issue?

**Comment by ChrisHughes** [comment]
No, this worked fine both without any ActiveRecord extensions, and with DbCharmer.

**Comment by mnelson** [comment]
Can you show your database.yml? Also, if you can throw some `puts` before and after the ActiveRecord calls to see how far you get that would be helpful.

**Comment by ChrisHughes** [comment]
I get past my activerecord calls fine, it finishes all execution in config/application.rb before trying to start rails itself.

My database.yml is as follows:

``` yaml
# MySQL.  Versions 4.1 and 5.0 are recommended.
#
# Install the MySQL driver:
#   gem install mysql2
#
# And be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html

common: &common
  adapter: makara_mysql2
  encoding: utf8
  reconnect: false
  pool: 5

dbs: &dbs
  <<: *common
  database: productname_development
  username: root
  password: ""
  socket: /tmp/mysql.sock
  makara: &makara_default
    <<: *makara_default
    connections:
      - role: master
        database: productname_development
      - role: slave
        database: productname_development_test

  productname:
    <<: *common
    database: productname_data
    username: root
    password: ""
    socket: /tmp/mysql.sock
    makara:
      <<: *makara_default
      connections:
        - role: master
          database: productname_data
        - role: slave
          database: productname_data

  drupal:
    <<: *common
    database: productname_drupal_test
    username: root
    password: ""
    socket: /tmp/mysql.sock
    makara:
      <<: *makara_default
      connections:
        - role: master
          database: productname_drupal_test
        - role: slave
          database: productname_drupal_test

  reporting:
    <<: *common
    database: productname_reports
    username: root
    password: ""
    socket: /tmp/mysql.sock
    makara:
      <<: *makara_default
      connections:
        - role: master
          database: productname_reports
        - role: slave
          database: productname_reports

development:
  <<: *dbs

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: productname_nodb
  pool: 5
  username: root
  password: ""
  socket: /tmp/mysql.sock

production:
  <<: *dbs
```

**Comment by mnelson** [comment]
One observation, though I don't think it's related, is that you use the makara_default config within the definition of makara_deafult:

``` yml
makara: &makara_default
    <<: *makara_default
    connections:
        - role: master
          database: productname_data
        - role: slave
          database: productname_data
```

should just be:

``` yml
makara: &makara_default
    connections:
        - role: master
          database: productname_data
        - role: slave
          database: productname_data
```

Not to mention unless makara_default defined more keys, there's no reason for it (all later usage defines the "connections" key).

Nothing jumps out at me. I would throw a debugger in and try to step into the application boot.

**Comment by ChrisHughes** [comment]
I noticed some possible errors in my previous database.yml. I've simplified how it passes makara's options. I'm still getting the stack too deep error with this new file.

``` yaml
# MySQL.  Versions 4.1 and 5.0 are recommended.
#
# Install the MySQL driver:
#   gem install mysql2
#
# And be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html

common: &common
  adapter: makara_mysql2
  encoding: utf8
  reconnect: false
  pool: 5

dbs: &dbs
  <<: *common
  database: productname_development
  username: root
  password: ""
  socket: /tmp/mysql.sock
  makara:
    blacklist_duration: &makara_default_blacklist_duration 5
    master_ttl: &makara_default_master_ttl 5
    sticky: &makara_default_sticky true
    rescue_connection_failures: &makara_default_rescue_connection_failures false
    connections:
      - role: master
        database: productname_development
      - role: slave
        database: productname_development_test

  productname:
    <<: *common
    database: productname_data
    username: root
    password: ""
    socket: /tmp/mysql.sock
    makara:
      blacklist_duration: *makara_default_blacklist_duration
      master_ttl: *makara_default_master_ttl
      sticky: *makara_default_sticky
      rescue_connection_failures: *makara_default_rescue_connection_failures
      connections:
        - role: master
          database: productname_data
        - role: slave
          database: productname_data

  drupal:
    <<: *common
    database: productname_drupal_test
    username: root
    password: ""
    socket: /tmp/mysql.sock
    makara:
      blacklist_duration: *makara_default_blacklist_duration
      master_ttl: *makara_default_master_ttl
      sticky: *makara_default_sticky
      rescue_connection_failures: *makara_default_rescue_connection_failures
      connections:
        - role: master
          database: productname_drupal_test
        - role: slave
          database: productname_drupal_test

  reporting:
    <<: *common
    database: productname_reports
    username: root
    password: ""
    socket: /tmp/mysql.sock
    makara:
      blacklist_duration: *makara_default_blacklist_duration
      master_ttl: *makara_default_master_ttl
      sticky: *makara_default_sticky
      rescue_connection_failures: *makara_default_rescue_connection_failures
      connections:
        - role: master
          database: productname_reports
        - role: slave
          database: productname_reports

development:
  <<: *dbs

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: productname_nodb
  pool: 5
  username: root
  password: ""
  socket: /tmp/mysql.sock

production:
  <<: *dbs
```

**Comment by ChrisHughes** [comment]
Another strange issue I run into is that rubymine running ruby-debug-ide hangs indefinitely on startup when my adapter is makara_mysql2. When the adapter is mysql2 it starts up right away in debug mode.

**Comment by ChrisHughes** [comment]
Seems to work fine if I switch to Rails 2.0.0, problem only occurs when Rails is 2.1.0

**Comment by mnelson** [comment]
What version of AR are you using? Makara requires 3.0+

**Comment by ChrisHughes** [comment]
3.2.16

**Comment by mnelson** [comment]
This seems app specific, closing.

**Comment by juancaldera** [comment]
just wanted to sound off on the same issue. On a brand new empty rails app with ruby 2.1.1, with this config

``` yaml
development: &development
  adapter: makara_mysql2
  encoding: utf8
  reconnect: false
  database: my_database
  pool: 5
  username: user
  password: pass

  makara:

    blacklist_duration: 5
    master_ttl: 5
    sticky: false
    rescue_connection_failures: true

    connections:
      - role: master
        host: 127.0.0.1
      - role: slave
        host: 127.0.0.1
      - role: slave
        host: 127.0.0.1
      - role: slave
        host: 192.168.10.2
```

The app will not start if a slave fails to connect giving a "stack level too deep" error. The same goes if a slave dies while the server is running.

 The gem works perfectly fine with Ruby 2.0.0-p451
