### ISSUE TITLE
Performance regression when upgrading to v0.2.2

### ISSUE THREAD

**Issue by briantobin** [taskrabbit/makara#51]
Hello! We are big fans of Makara at Storehouse. Yesterday we tried to update to v0.2.2 (we were on 362fe9f540). The specific SHA we deployed was 1ac718c7. Unfortunately it caused a big performance regression for us and we had to rollback. To give you an idea, this is our newrelic from yesterday:

![screen shot 2014-05-21 at 10 30 24 am](https://cloud.githubusercontent.com/assets/44727/3044118/634b65ee-e10e-11e3-8802-f690c551f960.png)

If we can be helpful in any way, please let us know. Sorry that I don't have more details to offer.

Brian

**Comment by mnelson** [comment]
Well that sucks, sorry about that. What's your db stack look like? From what I gathered we're talking v0.2.0 -> v0.2.2, correct? (https://github.com/taskrabbit/makara/compare/v0.2.0...v0.2.2)

**Comment by mnelson** [comment]
If you could get me a summarized version of your production database.yml that would be super helpful.

**Comment by mnelson** [comment]
- @davidjairala

**Comment by briantobin** [comment]
No problem, that's just how open source works sometimes! Hopefully we can turn the experience into something positive and fix a bug.

Our DB stack is pretty simple. App servers and postgres are all on EC2. We have a master and 2 slaves. Here's our database.yml template:

```
production:
    database: rails_{{rails_environment}}
    adapter: makara_postgresql
    password: {{rails_pgsql_password}}
    username: {{rails_environment}}

    makara:
      blacklist_duration: 5
      master_ttl: 5
      sticky: true
      rescue_connection_failures: true
      connections:
        - role: master
          host: {{ hostvars[groups['pgmaster'][0]]['ansible_ec2_local_ipv4'] }}
{% for host in groups['pgslave'] %}
        - role: slave
          host: {{hostvars[host]['ansible_default_ipv4']['address']}}
{% endfor %}
```

As for the versions we were transitioning between, we were pinned to 362fe9f5 because that's when `SELECT FOR UPDATE` was fixed to not execute on slaves. Looking at your releases, it seems to correlate with 0.2, yes. Here's a compare link with the specific SHA https://github.com/taskrabbit/makara/compare/362fe9f540bcafa75bf3a710482d9da1b97b3607...v0.2.2.
