### ISSUE TITLE
SELECTs not going to slave

### ISSUE THREAD

**Issue by lserman** [taskrabbit/makara#55]
Hello,

99% of my SELECTs are going to master. It is strange because there are a couple requests going to slave, but it's VERY rare. It seems like requests made to front end pages (an admin portal) go to slaves, but anything hitting our API (where all the traffic comes from) goes to master no matter what.

We are using Amazon RDS and the slave has had 100% uptime always. My config looks like this:

```
production: &production
  adapter: 'makara_mysql2'
  encoding: utf8
  database: 'mydbname'
  pool: 25
  timeout: 5000
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  port: 3306

  makara:
    blacklist_duration: 5
    master_ttl: 5
    sticky: true
    rescue_connection_failures: false

    connections:
      - role: master
        host: <%= ENV['DB_MASTER_HOST'] %>
      - role: slave
        host: <%= ENV['DB_SLAVE1_HOST'] %>

staging:
  <<: *production
```

I'm using Makara 0.2.2, Rails 4.1. Any thoughts?
