### ISSUE TITLE
Migrations are not properly working in rails 4.

### ISSUE THREAD

**Issue by shivaaqua** [taskrabbit/makara#61]
Whenever I run rake db:rollback, down migration are not running. 
I am using ruby2.1.2 and rails 4.1.1

I am using following config as well

```
development:
  adapter: makara_mysql2
  encoding: utf8
  database: mydb
  pool: 5
  username: root
  password: password
  host: localhost
  makara:
    # the following are default values
    blacklist_duration: 30
    master_ttl: 5
    sticky: true
    rescue_connection_failures: true
    connections:
      - role: master
        host: localhost
      - host: 192.168.1.2
        username: remoteuser
        password: password
```
